"""Renders a terraform.tfvars matching the exact variable names declared in
wordpress-high-traffic-aws/terraform/environments/example/variables.tf.

Values wp2aws can determine from sizing (instance types, counts, NAT strategy) are
filled in. Values that are inherently deployment-specific and not derivable from
analyzing a site (AMI ID, ACM certificate ARNs, domain names, the webhook secret) stay
as clearly marked REPLACE_ME placeholders, the same convention that repo's own
terraform.tfvars.example already uses.
"""

from __future__ import annotations

from ..models import SiteProfile
from .engine import SizingDecision

_TEMPLATE = """\
# Generated by wp2aws from a site scan. Values derived from the scan are filled in;
# REPLACE_ME placeholders are deployment-specific values wp2aws cannot determine from
# analyzing a site and must be filled in by hand, the same convention used in
# wordpress-high-traffic-aws's own terraform.tfvars.example.
#
# Sizing tier: {tier}
# Origin load at peak: {origin_req_per_sec:.1f} req/s
# Cache-hit-ratio assumption used: {cache_hit_ratio_used:.0%}

aws_region = "{aws_region}"

media_bucket_name = "REPLACE_ME-wp-media-bucket"

ami_id                  = "REPLACE_ME-ami-id"
alb_acm_certificate_arn = "arn:aws:acm:{aws_region}:REPLACE_ME:certificate/REPLACE_ME"

instance_type        = "{instance_type}"
app_min_size          = {app_min_size}
app_max_size          = {app_max_size}
app_desired_capacity  = {app_desired_capacity}

db_instance_class = "{db_instance_class}"
db_reader_count   = {db_reader_count}

redis_node_type           = "{redis_node_type}"
redis_num_cache_clusters  = {redis_num_cache_clusters}

single_nat_gateway = {single_nat_gateway}

domain_aliases                 = ["www.REPLACE_ME.com"]
cloudfront_acm_certificate_arn = "arn:aws:acm:us-east-1:REPLACE_ME:certificate/REPLACE_ME"

webhook_shared_secret = "REPLACE_ME-generate-a-long-random-value"
"""


def render_tfvars(decision: SizingDecision, profile: SiteProfile, aws_region: str = "us-east-1") -> str:
    return _TEMPLATE.format(
        tier=decision.tier,
        origin_req_per_sec=decision.origin_req_per_sec,
        cache_hit_ratio_used=decision.cache_hit_ratio_used,
        aws_region=aws_region,
        instance_type=decision.instance_type,
        app_min_size=decision.app_min_size,
        app_max_size=decision.app_max_size,
        app_desired_capacity=decision.app_desired_capacity,
        db_instance_class=decision.db_instance_class,
        db_reader_count=decision.db_reader_count,
        redis_node_type=decision.redis_node_type,
        redis_num_cache_clusters=decision.redis_num_cache_clusters,
        single_nat_gateway=str(decision.single_nat_gateway).lower(),
    )
